CREATE TABLE despesas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(120)  NOT NULL,
    valor          NUMERIC(12,2) NOT NULL,
    data           DATE          NOT NULL,
    categoria      VARCHAR(20)   NOT NULL,
    criado_em      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em  TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT ck_despesas_valor_positivo CHECK (valor > 0),
    CONSTRAINT ck_despesas_nome_nao_vazio CHECK (length(btrim(nome)) > 0)
);

-- A listagem padrao e "mais recentes primeiro", e o resumo filtra por periodo.
CREATE INDEX idx_despesas_data ON despesas (data DESC);

-- O resumo agrupa por categoria dentro de um periodo.
CREATE INDEX idx_despesas_categoria_data ON despesas (categoria, data DESC);
