CREATE TABLE usuarios (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(120) NOT NULL,
    email          VARCHAR(180) NOT NULL,
    -- BCrypt tem 60 caracteres. A senha em texto puro não existe em lugar nenhum.
    senha_hash     VARCHAR(72)  NOT NULL,
    criado_em      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    atualizado_em  TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT ck_usuarios_nome_nao_vazio  CHECK (length(btrim(nome)) > 0),
    CONSTRAINT ck_usuarios_email_com_arroba CHECK (position('@' in email) > 1)
);

-- O e-mail é normalizado para minúsculas na aplicação; o índice único garante
-- a regra mesmo se alguém inserir direto no banco.
CREATE UNIQUE INDEX ux_usuarios_email ON usuarios (email);

-- ---------------------------------------------------------------------------
-- Vincula cada despesa a um dono.
-- ---------------------------------------------------------------------------

ALTER TABLE despesas ADD COLUMN usuario_id BIGINT;

-- Esta migration foi escrita antes do primeiro deploy: qualquer linha existente
-- aqui é dado de teste local e não tem dono possível para receber.
DELETE FROM despesas WHERE usuario_id IS NULL;

ALTER TABLE despesas ALTER COLUMN usuario_id SET NOT NULL;

ALTER TABLE despesas
    ADD CONSTRAINT fk_despesas_usuario
    FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE;

-- A partir daqui NENHUMA consulta roda sem filtrar por usuario_id, então os
-- índices antigos (sem o dono na frente) deixam de servir.
DROP INDEX idx_despesas_data;
DROP INDEX idx_despesas_categoria_data;

CREATE INDEX idx_despesas_usuario_data ON despesas (usuario_id, data DESC);
CREATE INDEX idx_despesas_usuario_categoria_data ON despesas (usuario_id, categoria, data DESC);
