-- Uma conta passa a ter duas formas de entrar: senha ou Google. Pelo menos
-- uma das duas precisa existir, e o e-mail é o que liga as duas.

ALTER TABLE usuarios ADD COLUMN google_id            VARCHAR(64);
ALTER TABLE usuarios ADD COLUMN email_confirmado_em  TIMESTAMP(6) WITH TIME ZONE;

-- Quem entra pelo Google nunca escolhe senha.
ALTER TABLE usuarios ALTER COLUMN senha_hash DROP NOT NULL;

ALTER TABLE usuarios
    ADD CONSTRAINT ck_usuarios_tem_credencial CHECK (senha_hash IS NOT NULL OR google_id IS NOT NULL);

-- Índice parcial: vários usuários podem ter google_id nulo, mas o mesmo id do
-- Google não pode apontar para duas contas.
CREATE UNIQUE INDEX ux_usuarios_google_id ON usuarios (google_id) WHERE google_id IS NOT NULL;

-- As contas que já existiam são anteriores a esta funcionalidade. Marcá-las
-- como confirmadas evita trancar do lado de fora quem já estava usando.
UPDATE usuarios SET email_confirmado_em = now() WHERE email_confirmado_em IS NULL;

-- ---------------------------------------------------------------------------
-- Tokens de uso único: confirmação de e-mail e recuperação de senha.
-- ---------------------------------------------------------------------------

CREATE TABLE tokens_de_acesso (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT      NOT NULL,
    tipo        VARCHAR(24) NOT NULL,
    -- Só o SHA-256 do token, nunca o token. Se este banco vazar, os links que
    -- estiverem em trânsito continuam inúteis para quem leu a tabela.
    token_hash  VARCHAR(64) NOT NULL,
    expira_em   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    usado_em    TIMESTAMP(6) WITH TIME ZONE,
    criado_em   TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_tokens_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_tokens_hash ON tokens_de_acesso (token_hash);
CREATE INDEX idx_tokens_usuario_tipo ON tokens_de_acesso (usuario_id, tipo);
